apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: template-spring-boot-build-task
spec:
  inputs:
    resources:
      - name: git-source
        type: git
  steps:
    - name: build
      image: gradle:jdk11
      workingdir: ${inputs.resources.git-source.path}
      command:
        - /bin/bash
      args:
        - -c
        - |
          set -x
          ./gradlew assemble --no-daemon
    - name: test
      image: gradle:jdk11
      workingdir: ${inputs.resources.git-source.path}
      command:
        - /bin/bash
      args:
        - -c
        - |
          set -x
          ./gradlew testClasses --no-daemon
    - name: sonar-scan
      image: gradle:jdk11
      workingdir: ${inputs.resources.git-source.path}
      # env:
      # - name: "SONARQUBE_URL"
      #   value:
      # - name: "SONARQUBE_USER"
      #   value:
      # - name: "SONARQUBE_PASSWORD"
      #   value:
      command:
        - /bin/bash
      args:
        - -c
        - |
          if [[ -z "${SONARQUBE_URL}" ]]; then
            echo "Skipping Sonar Qube step as Sonar Qube not installed or configured"
            exit 0
          fi
          set -x
          ./gradlew -Dsonar.login=${SONARQUBE_USER} -Dsonar.password=${SONARQUBE_PASSWORD} -Dsonar.host.url=${SONARQUBE_URL} sonarqube
